# Generated by Django 5.1.7 on 2025-03-21 13:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("players", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="equipment",
            name="player",
            field=models.ManyToManyField(
                blank=True, related_name="equipments", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="player",
            name="race",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="players.race",
            ),
        ),
    ]
